# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180617_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
